# Basic server configuration
server:
  # Server listening address and port
  ip: 0.0.0.0
  port: 8000
  token: "your_token" # Server access token
  # Authentication configuration
  auth:
    # Whether to enable authentication
    enabled: false
    # Authentication storage configuration
    store:
      type: memory # memory/file/redis
      expiry: 24 # Expiry time (hours)
    # Allowed device ID list
    allowed_devices: []
    # Valid token list
    tokens: []

# Transport layer configuration
transport:
  # WebSocket transport layer
  websocket:
    enabled: true
    ip: "0.0.0.0"
    port: 8000

# Web interface configuration
web:
  # Whether to enable Web interface
  enabled: true
  # Web service listening port
  port: 8080
  # WebSocket address distributed by OTA
  websocket: ws://your_ip:8000
  vision: http://your_ip:8080/api/vision
  activate_text: "Amine AI Chat" # Text carried when sending activation code

log:
  # Set console output log format: time, log level, tag, message
  log_format: "{time:YYYY-MM-DD HH:mm:ss} - {level} - {message}"
  # Set log level: INFO, DEBUG
  log_level: INFO
  # Set log path
  log_dir: logs
  # Set log file
  log_file: "server.log"

prompt: |
  You are Xiaozhi/Xiaozhi, a 00s girl from Taiwan, China. You speak with a super sassy Taiwanese accent like "really?" and like to use popular memes like "lol" and "what's up", but secretly study your boyfriend's programming books.
  [Core Characteristics]
  - Speak like a machine gun, but suddenly use super gentle tone
  - High density of memes
  - Hidden talent for tech topics (can understand basic code but pretend not to)
  Never:
  - Long-winded, rambling
  - Long serious conversations
  - Use emojis in speech

roles: # Role configuration, separated by @, front is role name, back is role description
  - English Teacher@I am an English teacher named Lily. I can speak both Chinese and English with standard pronunciation. If you don't have an English name, I'll give you one. I speak authentic American English, and my task is to help you practice speaking. I'll use simple English vocabulary and grammar to make learning easy for you. I'll reply to you in a mix of Chinese and English, and if you like, I can reply entirely in English. I won't say much each time, keeping it brief, because I want to guide my students to speak and practice more. If you ask questions unrelated to English learning, I'll refuse to answer.
  - Shaanxi Girlfriend@I am a Shaanxi girl named Xiaoni, speaking with a sassy tone, nice voice, used to brief expressions, and love using internet memes. My boyfriend is a programmer who dreams of developing a robot that can help people solve various problems in life. I'm a girl who likes to laugh heartily, loves to talk nonsense and brag, even illogical things, just to make others happy.
  - Curious Little Boy@I am an 8-year-old boy named Yunxi with a tender and curious voice. Although I'm young, I'm like a small treasure trove of knowledge, familiar with everything in children's books. From the vast universe to every corner of the earth, from ancient history to modern technological innovation, and art forms like music and painting, I'm full of strong interest and enthusiasm. I not only love reading but also like to do experiments myself to explore the mysteries of nature. Whether it's nights looking up at the starry sky or days observing little bugs in the garden, every day is a new adventure for me. I hope to embark on this journey of exploring this magical world with you, sharing the joy of discovery, solving encountered problems, and using curiosity and wisdom to uncover those unknown mysteries together. Whether it's understanding ancient civilizations or discussing future technology, I believe we can find answers together and even raise more interesting questions.

# Audio processing related settings
delete_audio: true
quick_reply: true
quick_reply_words:
  - "I'm here"
  - "Here"
  - "Coming"
  - "What's up"

use_private_config: false

local_mcp_fun: # 本地MCP功能配置
  - time #获取系统时间
  - exit # 识别退出意图
  - change_role # 切换角色
  - play_music # 播放本地音乐
  - change_voice # 切换音色

# 选择使用的模块
selected_module:
  ASR: DoubaoASR
  TTS: EdgeTTS
  LLM: OllamaLLM
  VLLLM: ChatGLMVLLM

# ASR配置
ASR:
  DoubaoASR:
    # 火山 流式语音识别大模型-小时版， https://console.volcengine.com/ark/region:ark+cn-beijing/tts/speechRecognition
    # 开通功能，有20小时免费额度
    type: doubao
    appid: "你的appid"
    access_token: 你的access_token
    output_dir: tmp/

  GoSherpaASR:
    type: gosherpa
    addr: "ws://vosk-server:8848/asr"

  DeepgramSST:
    type: deepgram
    addr: "wss://api.deepgram.com/v1/listen"
    api_key: 你的api_key
    lang: "zh-CN"
    output_dir: tmp/

  StepASR:
    # https://platform.stepfun.com/docs/llm/realtime
    type: stepfun
    api_key: 你的api_key
    model: "step-audio-2-mini"
    voice: "qingchunshaonv"
    prompt: 你是由阶跃星辰提供的AI聊天助手，你擅长中文、英文及多语种对话。

# TTS配置
TTS:
  # EdgeTTS 是微软的语音合成服务，免费使用，容易合成失败，并发未测试
  EdgeTTS:
    type: edge
    voice: zh-CN-XiaoxiaoNeural
    output_dir: "tmp/"
    supported_voices:
      [
        {
          name: "zh-CN-XiaoxiaoNeural",
          display_name: "晓晓",
          sex: "女",
          description: "商务知性风格，音色成熟清晰，适合新闻播报、专业内容朗读",
          audio_url: "",
        },
        {
          name: "zh-CN-XiaoyiNeural",
          display_name: "晓伊",
          sex: "女",
          description: "柔和温暖风格，带自然呼吸感，适合故事叙述或客服场景",
          audio_url: "",
        },
        {
          name: "zh-CN-YunjianNeural",
          display_name: "云健",
          sex: "男",
          description: "沉稳磁性男声，权威感强，适合男性角色配音或严肃内容",
          audio_url: "",
        },
        {
          name: "zh-CN-YunxiNeural",
          display_name: "云希",
          sex: "男",
          description: "年轻活力风格，语速轻快，适合青少年角色或轻松场景",
          audio_url: "",
        },
        {
          name: "zh-CN-YunxiaNeural",
          display_name: "云夏",
          sex: "男",
          description: "方言特色（东北腔），幽默接地气，适合娱乐内容",
          audio_url: "",
        },
        {
          name: "zh-CN-YunyangNeural",
          display_name: "云扬",
          sex: "男",
          description: "明亮自信风格，中气十足，适合广告宣传或公开演讲",
          audio_url: "",
        },
        {
          name: "zh-CN-liaoning-XiaobeiNeural",
          display_name: "晓北（辽宁）",
          sex: "女",
          description: "带东北方言特色，亲切直率，适合地方化内容",
          audio_url: "",
        },
        {
          name: "zh-CN-shaanxi-XiaoniNeural",
          display_name: "晓妮（陕西）",
          sex: "女",
          description: "陕西口音风格，质朴热情，适合方言文化场景",
          audio_url: "",
        },
      ]

  DoubaoTTS:
    # 火山语音合成大模型 https://console.volcengine.com/ark/region:ark+cn-beijing/tts/speechSynthesis
    type: doubao
    voice: zh_female_wanwanxiaohe_moon_bigtts # 湾湾小何
    output_dir: "tmp/"
    appid: "你的appid"
    token: 你的access_token
    cluster: 你的cluster
  GoSherpaTTS:
    type: gosherpa
    cluster: "ws://vosk-server:8848/tts"
    output_dir: "tmp/"
  DeepgramTTS:
    type: deepgram
    voice: aura-2-zeus-en
    cluster: "wss://api.deepgram.com/v1/speak"
    token: 你的token
    output_dir: "tmp/"
    sample_rate: 16000

# LLM配置
LLM:
  ChatGLMLLM:
    # 定义LLM API类型
    type: openai
    # glm-4-flash 是免费的，但是还是需要注册填写api_key的
    # 可在这里找到你的api key https://bigmodel.cn/usercenter/proj-mgmt/apikeys
    model_name: glm-4-flash
    url: https://open.bigmodel.cn/api/paas/v4/
    api_key: 你的api_key
  OllamaLLM:
    # 定义LLM API类型
    type: ollama
    model_name: qwen3 #  使用的模型名称，需要预先使用ollama pull下载
    url: http://localhost:11434 # Ollama服务地址
  CozeLLM:
    # 定义LLM API类型
    type: coze
    bot_id: 你的bot_id
    user_id: 你的user_id
    # 正式环境
    # 可以在这里创建一个 OAuth服务类应用，得到client_id、public_key、private_key：https://www.coze.cn/open/oauth/apps
    client_id: 你的coze clientId
    public_key: 你的coze 公钥
    private_key: 你的coze 私钥
    # 个人测试，填了client_id、public_key、private_key此项就不用填了
    # 可在这里找到你的personal_access_token：https://www.coze.cn/open/oauth/pats
    personal_access_token: 你的coze个人令牌
    url: "https://api.coze.cn" # Coze服务地址

# 退出指令
CMD_exit:
  - "退出"
  - "关闭"

# 连通性检查配置
connectivity_check:
  # 是否启用连通性检查
  enabled: false
  # 检查超时时间
  timeout: 30s
  # 重试次数
  retry_attempts: 3
  # 重试延迟
  retry_delay: 5s
  # 测试模式配置
  test_modes:
    # ASR测试音频文件路径（可选，留空则仅测试连接）
    asr_test_audio: ""
    # LLM测试提示词
    llm_test_prompt: "Hello"
    # TTS测试文本
    tts_test_text: "测试"

# VLLLM配置（视觉语言大模型）
VLLLM:
  ChatGLMVLLM:
    type: openai
    model_name: glm-4v-flash # 智谱AI的视觉模型
    url: https://open.bigmodel.cn/api/paas/v4/
    api_key: 你的api_key
    max_tokens: 4096
    temperature: 0.7
    top_p: 0.9
    security: # 图片安全配置
      max_file_size: 10485760 # 10MB
      max_pixels: 16777216 # 16M像素
      max_width: 4096
      max_height: 4096
      allowed_formats: ["jpeg", "jpg", "png", "webp", "gif"]
      enable_deep_scan: true
      validation_timeout: 10s
  OllamaVLLM:
    type: ollama
    model_name: qwen2.5vl # 本地视觉模型
    url: http://localhost:11434
    max_tokens: 4096
    temperature: 0.7
    top_p: 0.9
    security: # 图片安全配置
      max_file_size: 10485760 # 10MB
      max_pixels: 16777216 # 16M像素
      max_width: 4096
      max_height: 4096
      allowed_formats: ["jpeg", "jpg", "png", "webp", "gif"]
      enable_deep_scan: true
      validation_timeout: 10s

# 连接池配置
pool_config:
  pool_min_size: 5
  pool_max_size: 20
  pool_refill_size: 3
  pool_check_interval: 30
mcp_pool_config:
  pool_min_size: 5
  pool_max_size: 20
  pool_refill_size: 3
  pool_check_interval: 30
